name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        - name: setup-flutter
  uses: takuyaohashi/setup-flutter@v1
  with:
    # The Flutter version to download
    flutter-version: # optional, default is latest
    # The Flutter channel to download
    channel: # optional, default is stable
